parameters:
  project: ''
  name: ''

jobs:

  - job: ${{ parameters.name }}_debug_Build
    displayName: ${{ parameters.name }}_debug
    pool:
      vmImage: 'macos-latest'
    variables:
      - group: AgoraLive
      - group: AgoraVoice

    steps:
      - script: cd ${{ parameters.project }} && chmod +x ./build-templates/build-debug.sh && ./build-templates/build-debug.sh
        env:
          appId: $(appId.debug)
          customerId: $(customer.id)
          customerCert: $(customer.cer)
          buglyId: $(bugly_appId_android)

      - task: CopyFiles@2
        inputs:
          Contents: '**/*.apk'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true

      - script: cd ${{ parameters.project }} && chmod +x ./build-templates/build-rename.sh && ./build-templates/build-rename.sh
        env:
          path: '$(Build.ArtifactStagingDirectory)'
          appName: $(appName.debug)
          ver: $(appVer)

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: ${{ parameters.name }}