# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraVoice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraVoice
  platform :ios, '9.0'

  pod 'RxSwift', '~> 5.0.1'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'MJRefresh', '~> 3.3.1'
  pod 'FLAnimatedImage'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'AgoraRtm_iOS', '~> 1.2.2'
  pod 'AgoraRtcEngine_iOS', '~> 3.0.1'
  pod 'AlamoClient', '~> 1.0.3'
  pod 'AliyunOSSiOS'
  pod 'Bugly'
  pod 'SSZipArchive'
end
